301 view for who has lent a specific item in the past
Bellettrie/library_system pull request #528
Opened 2024-04-09 17:40 UTC by KylianvD

I spend far, far, far too long on making this work properly. I do hope I didn't accidentally duct tape something.

2024-04-11 07:24 UTC, RemcoSwenker requested changes
Unfortunately you did duct tape some things. I'm missing a html file that display's the table. because when I go to http://127.0.0.1:8000/lend/history/6629 I get a very nice error.

2024-04-11 07:48 UTC, nanderv commented
> Unfortunately you did duct tape some things. I'm missing a html file that display's the table. because when I go to http://127.0.0.1:8000/lend/history/6629 I get a very nice error.

@KylianvD  I think you just forgot to commit the history.html file :).

2024-04-11 11:34 UTC, RemcoSwenker commented on lendings/views/lending_history.py
> +    paginate_by = 50
Paginate 50 is allot do we want that?

2024-04-12 12:03 UTC, RemcoSwenker approved these changes

2024-04-12 12:08 UTC, merged